import"./assets/modulepreload-polyfill-B5Qt9EMX.js";/* empty css                      */import{i as r,a as y,S as g}from"./assets/vendor-BIHATn4Y.js";const u="45947760-a7d8d36d32b01afaf5acf1299",f=document.querySelector(".search-form"),m=document.querySelector(".gallery"),l=document.querySelector("#loader"),t=document.createElement("button");t.textContent="Load more";t.classList.add("load-more");document.body.append(t);t.style.display="none";let c="",s=1,p=40,i;async function h(e,n){const a=`https://pixabay.com/api/?key=${u}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${p}`;try{l.style.display="block";const o=await y.get(a);return l.style.display="none",o.data}catch(o){return console.error("Błąd w zapytaniu:",o),l.style.display="none",r.error({title:"Error",message:"Problem with fetching images"}),{hits:[],totalHits:0}}}function b(e){s===1&&(m.innerHTML="");const n=e.map(a=>`
    <a href="${a.largeImageURL}" class="gallery-item">
      <img src="${a.webformatURL}" alt="${a.tags}" />
      <div class="image-info">
        <p><span class="image-info-label">Likes:</span> <span class="image-info-value">${a.likes}</span></p>
        <p><span class="image-info-label">Views:</span> <span class="image-info-value">${a.views}</span></p>
        <p><span class="image-info-label">Comments:</span> <span class="image-info-value">${a.comments}</span></p>
        <p><span class="image-info-label">Downloads:</span> <span class="image-info-value">${a.downloads}</span></p>
      </div>
    </a>
  `).join("");m.insertAdjacentHTML("beforeend",n),i?i.refresh():i=new g(".gallery-item",{captionsData:"alt",captionDelay:250})}async function d(){const e=await h(c,s);if(e.hits.length===0&&s===1){r.info({iconUrl:"./src/img/no-images-icon.png",message:"Sorry, there are no images matching your search query. Please, try again!",backgroundColor:"#EF4040"}),t.style.display="none";return}if(b(e.hits),e.hits.length<p||s*p>=e.totalHits?(t.style.display="none",r.info({message:"We're sorry, but you've reached the end of search results."})):t.style.display="block",s>1){const{height:n}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}f.addEventListener("submit",async e=>{e.preventDefault(),c=document.querySelector("#query").value.trim(),c&&(s=1,t.style.display="none",await d())});t.addEventListener("click",async()=>{s+=1,await d()});
//# sourceMappingURL=page-2.js.map
